class Machine:

    def __init__(self, name, speed):
        self.name = name
        self.speed = speed
        self.is_running = False

    def start(self):
        self.is_running = True
        print(f"{self.name} started at speed {self.speed}")

    def stop(self):
        self.is_running = False
        print(f"{self.name} stopped")

    def __str__(self):
        return f"Machine: {self.name} | Speed: {self.speed}"


class CNCMachine(Machine):

    def __init__(self, name, speed, tool_type):
        super().__init__(name, speed)   # runs Machine's __init__
        self.tool_type = tool_type      # adds CNC-specific attribute

    def cut(self):
        if self.is_running:
            print(f"{self.name} cutting with {self.tool_type}")
        else:
            print(f"{self.name} is not running, start it first")

    def __str__(self):
        return f"CNC Machine: {self.name} | Tool: {self.tool_type} | Speed: {self.speed}"


# Machine objects
m1 = Machine("Conveyor Belt", 300)
m1.start()
print(m1)

print("---")

# CNCMachine inherits everything from Machine + has its own stuff
cnc1 = CNCMachine("CNC Lathe", 1500, "Drill Bit")
cnc1.start()    # inherited from Machine
cnc1.cut()      # CNC's own method
print(cnc1)     # CNC's own __str__


class EmergencyMachine(Machine):

    def __init__(self, name, speed, emergency_level):
        super().__init__(name, speed)
        self.emergency_level = emergency_level

    def start(self):                          # overrides Machine's start()
        if self.emergency_level == "high":
            print(f"⚠ EMERGENCY START: {self.name} running at max capacity!")
        else:
            super().start()                   # calls Machine's original start()
        self.is_running = True

    def __str__(self):
        return f"Emergency Machine: {self.name} | Level: {self.emergency_level}"


e1 = EmergencyMachine("Backup Generator", 500, "high")
e2 = EmergencyMachine("Cooling System", 200, "low")

e1.start()
e2.start()
print(e1)
print(e2)


class RoboticCNC(CNCMachine):

    def __init__(self, name, speed, tool_type, ai_model):
        super().__init__(name, speed, tool_type)
        self.ai_model = ai_model

    def auto_cut(self):
        self.start()
        print(f"{self.name} using AI model '{self.ai_model}' to cut automatically")
        self.cut()

    def __str__(self):
        return f"Robotic CNC: {self.name} | AI: {self.ai_model} | Tool: {self.tool_type}"


r1 = RoboticCNC("RoboLathe X1", 2000, "Laser Cutter", "GPT-Motion v2")
r1.auto_cut()
print(r1)

print("-"*70)
#__repr__ 

class Sensor:

    def __init__(self, sensor_id, sensor_type, value):
        self.sensor_id = sensor_id
        self.sensor_type = sensor_type
        self.value = value

    def __str__(self):
        return f"Sensor {self.sensor_id}: {self.value} ({self.sensor_type})"

    def __repr__(self):
        return f"Sensor(sensor_id={self.sensor_id!r}, sensor_type={self.sensor_type!r}, value={self.value!r})"


s1 = Sensor("S001", "Temperature", 72.5)
s2 = Sensor("S002", "Pressure", 101.3)

print(s1)           # calls __str__
print(repr(s1))     # calls __repr__

sensors = [s1, s2]
print(sensors)      # lists call __repr__ on each item  


print("-"*70)

from dataclasses import dataclass, field


@dataclass
class WorkOrder:
    order_id: str
    product: str
    quantity: int
    priority: str = "normal"        # default value
    completed: bool = False         # default value

    def complete(self):
        self.completed = True
        print(f"Order {self.order_id} completed")

    def __str__(self):
        status = "✓" if self.completed else "pending"
        return f"[{status}] {self.order_id} | {self.product} x{self.quantity} | {self.priority}"


w1 = WorkOrder("WO001", "Steel Bolt", 500)
w2 = WorkOrder("WO002", "Aluminum Plate", 200, priority="high")
w3 = WorkOrder("WO003", "Titanium Rod", 50, priority="urgent")

print(w1)
print(w2)
print(w3)

print(repr(w1))     # __repr__ is auto-generated by dataclass

w2.complete()
print(w2)